# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SMOO' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SMOO
  pod 'GoogleMaps', '4.1.0'
  target 'SMOOTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SMOOUITests' do
    # Pods for testing
  end

end
